services:
  - type: web
    name: vivero-rocio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
